version: "3.4"
services:
  geobaserow:
    container_name: geobaserow
    image: geobaserow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      BASEROW_PUBLIC_URL: http://localhost
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data: