# Generated by Django 5.0.9 on 2024-12-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("database", "0173_datasyncsyncedproperty_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiPolygonField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.field",
                    ),
                ),
                (
                    "default_center_lat",
                    models.FloatField(
                        default=0, help_text="The default center latitude of the map."
                    ),
                ),
                (
                    "default_center_lon",
                    models.FloatField(
                        default=0, help_text="The default center longitude of the map."
                    ),
                ),
                (
                    "default_zoom",
                    models.IntegerField(
                        default=4, help_text="The default zoom level of the map."
                    ),
                ),
                (
                    "basemap",
                    models.CharField(
                        choices=[
                            ("voyager", "Voyager - Colored map"),
                            ("positron", "Positron - Light gray map"),
                            ("dark-matter", "Dark Matter - Dark gray map"),
                        ],
                        default="voyager",
                        help_text="The basemap of the map.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.field", models.Model),
        ),
        migrations.CreateModel(
            name="PointField",
            fields=[
                (
                    "field_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.field",
                    ),
                ),
                (
                    "default_center_lat",
                    models.FloatField(
                        default=0, help_text="The default center latitude of the map."
                    ),
                ),
                (
                    "default_center_lon",
                    models.FloatField(
                        default=0, help_text="The default center longitude of the map."
                    ),
                ),
                (
                    "default_zoom",
                    models.IntegerField(
                        default=4, help_text="The default zoom level of the map."
                    ),
                ),
                (
                    "basemap",
                    models.CharField(
                        choices=[
                            ("voyager", "Voyager - Colored map"),
                            ("positron", "Positron - Light gray map"),
                            ("dark-matter", "Dark Matter - Dark gray map"),
                        ],
                        default="voyager",
                        help_text="The basemap of the map.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("database.field", models.Model),
        ),
        migrations.CreateModel(
            name="MapView",
            fields=[
                (
                    "view_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="database.view",
                    ),
                ),
                (
                    "geo_field",
                    models.ForeignKey(
                        blank=True,
                        help_text="One of the supported geo fields that the map view will be based on.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_view_gep_field",
                        to="database.field",
                    ),
                ),
            ],
            options={
                "db_table": "geobaserow_mapview",
            },
            bases=("database.view",),
        ),
        migrations.CreateModel(
            name="MapViewFieldOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Whether or not the field should be hidden in the popup.",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=32767,
                        help_text="The order that the field has in the view. Lower value is first.",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.field"
                    ),
                ),
                (
                    "map_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geobaserow.mapview",
                    ),
                ),
            ],
            options={
                "db_table": "geobaserow_mapviewfieldoptions",
                "ordering": ("order", "field_id"),
                "unique_together": {("map_view", "field")},
            },
        ),
        migrations.AddField(
            model_name="mapview",
            name="field_options",
            field=models.ManyToManyField(
                through="geobaserow.MapViewFieldOptions", to="database.field"
            ),
        ),
    ]
